services:
  - type: web
    name: metar-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: 71cad267b678677801d1499b3dd10f5e
        generateValue: true
      - key: POLL_INTERVAL
        value: 300
      - key: DB_PATH
        value: /tmp/metar_history.db
